#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '..');
export const DATA_DIR = path.join(ROOT, 'course', 'data');
export const BUNDLE_PATH = path.join(DATA_DIR, 'vocab-bundle.js');

// Spanish word characters (letters, including accented and ñ).
const WORD_RE = /[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g;

/** Lowercase and strip accents so "México" === "mexico". */
export function normalize(word) {
  return String(word)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/** Split a passage into normalized-ish word tokens (keeps original form). */
export function tokenize(text) {
  return String(text).match(WORD_RE) || [];
}

export function loadLessons(dir = DATA_DIR) {
  return fs.readdirSync(dir)
    .filter(f => /^lesson-\d+\.json$/.test(f))
    .sort((a, b) => Number(a.match(/\d+/)[0]) - Number(b.match(/\d+/)[0]))
    .map(f => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')));
}

export function loadDict(dir = DATA_DIR) {
  const lessons = loadLessons(dir);
  const words = new Set();   // normalized words that have been TAUGHT
  const seen = new Set();    // normalized words that have APPEARED anywhere
  const wordInfo = new Map();
  for (const lesson of lessons) {
    for (const w of lesson.words || []) {
      if (!w || !w.word) continue;
      const key = normalize(w.word);
      if (!words.has(key)) {
        words.add(key);
        wordInfo.set(key, { lesson: lesson.lesson, title: lesson.title, ext: !!w.ext, word: w.word });
      }
      // Multi-word entries ("me llamo", "buenos días") teach each token too.
      for (const t of tokenize(w.word)) seen.add(normalize(t));
      if (w.example && w.example.es) {
        for (const t of tokenize(w.example.es)) seen.add(normalize(t));
      }
    }
  }
  return { lessons, words, seen, wordInfo };
}

export function findNewWords(text, dict) {
  const newWords = [];
  const known = [];
  const seenHere = new Set();
  for (const tok of tokenize(text)) {
    const key = normalize(tok);
    if (seenHere.has(key)) continue;
    seenHere.add(key);
    if (dict.words.has(key) || dict.seen.has(key)) { known.push(tok); continue; }
    newWords.push(tok);
  }
  return { newWords, known };
}

export function lookup(word, dict) {
  return dict.wordInfo.get(normalize(word)) || null;
}

export function buildBundle(dir = DATA_DIR, out = BUNDLE_PATH) {
  const lessons = loadLessons(dir);
  const header =
    '// AUTO-GENERATED by scripts/vocab.mjs (command: build). DO NOT edit by hand.\n' +
    '// Source: course/data/lesson-*.json\n';
  fs.writeFileSync(out, header + 'window.VOCAB = ' + JSON.stringify(lessons, null, 2) + ';\n', 'utf8');
  return out;
}

function pad(n) { return String(n).padStart(2, '0'); }

function printNew(result) {
  if (!result.newWords.length) {
    console.log('No new words — everything in this passage has been taught.');
    return;
  }
  console.log('NEW WORDS (not in the taught list):');
  for (const w of result.newWords) console.log('  - ' + w);
  console.log('\nAlready taught: ' + result.known.length + ' words.');
}

const USAGE = `vocab.mjs — vocabulary manager for the Spanish course

Usage:
  node scripts/vocab.mjs new "<passage>"     list words not taught yet in a passage
  node scripts/vocab.mjs new --file <path>    read the passage from a file
  node scripts/vocab.mjs lookup <word>        which lesson taught this word
  node scripts/vocab.mjs stats                statistics
  node scripts/vocab.mjs build                regenerate course/data/vocab-bundle.js`;

function main() {
  const [cmd, ...args] = process.argv.slice(2);
  const dict = loadDict();

  if (cmd === 'new') {
    const fi = args.indexOf('--file');
    const text = fi !== -1 ? fs.readFileSync(args[fi + 1], 'utf8') : args.join(' ');
    if (!text.trim()) { console.error('Missing passage.\n\n' + USAGE); process.exit(1); }
    printNew(findNewWords(text, dict));
  } else if (cmd === 'lookup') {
    const word = args[0];
    if (!word) { console.error('Missing word.\n\n' + USAGE); process.exit(1); }
    const info = lookup(word, dict);
    if (info) {
      console.log(`${word} — taught in Lesson ${pad(info.lesson)} (${info.title})` +
        (info.ext ? ' [extension word]' : ''));
    } else {
      console.log(`${word} — NOT in the taught list.`);
    }
  } else if (cmd === 'stats') {
    const total = dict.lessons.reduce((s, l) => s + (l.words || []).length, 0);
    const ext = dict.lessons.reduce((s, l) => s + (l.words || []).filter(w => w.ext).length, 0);
    console.log('Lessons: ' + dict.lessons.length);
    console.log('Total vocabulary entries: ' + total + ' (' + (total - ext) + ' core + ' + ext + ' extension)');
    console.log('Unique words taught: ' + dict.words.size);
    console.log('Unique words appeared: ' + dict.seen.size);
  } else if (cmd === 'build') {
    const out = buildBundle();
    console.log('Bundle written: ' + path.relative(ROOT, out));
  } else {
    console.log(USAGE);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
